name: Caller

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  reusable:
    name: Reusable
    uses: reed-hanger/reusable-workflow-bug/.github/workflows/reusable.yaml@test
    secrets:
      arbitrary: |
        TEST = "${{ secrets.EXAMPLE_SECRET }}"
        TEST2 = "${{ vars.MY_VAR }}"
