name: Terraform AWS Environments

on:
  workflow_call:
    secrets:
      arbitrary:
        required: true
      mask:
        required: true

jobs:
  testing:
    name: Verify Bug
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - name: Output arbitrary k/v pairs to env vars
        env:
          JSON_DOC: ${{ secrets.mask }}
        run: |
          printf '%s\n' "$JSON_DOC" | jq 'to_entries | .[].value' -r | xargs -L1 -I'{}' echo ::add-mask::{}
          #echo "${{ secrets.arbitrary }}" >> $GITHUB_ENV
      - name: Separate step to test secrets again
        run: |
          echo $TEST
          echo $TEST2
          echo $TEST | base64
          echo $TEST2 | base64
