name: Terraform AWS Environments

on: workflow_call

jobs:
  testing:
    name: Verify Bug
    runs-on: ubuntu-latest
    steps:
      - name: Output inherited secrets to env var
        run: |
          echo "test=${{ secrets.TEST }}" >> $GITHUB_ENV
          echo "test2=${{ secrets.TEST2 }}" >> $GITHUB_ENV
      - name: Mask all secrets
        run: |
          echo $test
          echo $test2
