name: Terraform AWS Environments

on:
  workflow_call:
    secrets:
      arbitrary:
        required: true
      mask:
        required: true

jobs:
  testing:
    name: Verify Bug
    runs-on: ubuntu-latest
    steps:
      - name: Output arbitrary k/v pairs to env vars
        run: |
          echo "${{ secrets.mask }}" | jq 'keys' -r
          echo "${{ secrets.arbitrary }}" >> $GITHUB_ENV
      - name: Separate step to test secrets again
        run: |
          echo $TEST
          echo $TEST2
