name: Terraform AWS Environments

on:
  workflow_call:
    inputs:
      arbitrary:
        required: true
        type: string

jobs:
  testing:
    name: Verify Bug
    runs-on: ubuntu-latest
    steps:
      - name: Output arbitrary k/v pairs to env vars
        run: echo "${{ inputs.arbitrary }}" >> $GITHUB_ENV
      - name: Echo individual secrets
        run: |
          echo $TEST
          echo $TEST2
